chore: replace black with ruff as the formatter
canonical/openfga-operator pull request #52
Opened 2024-05-22 00:17 UTC by wood-push-melon

2024-05-22 07:50 UTC, BarcoMasile approved these changes

2024-05-22 07:52 UTC, natalian98 commented on pyproject.toml
> +[too.ruff.lint]
```suggestion
[tool.ruff.lint]
```

2024-05-22 07:52 UTC, natalian98 commented on pyproject.toml
> +[too.ruff.lint.flake8-copyright]
```suggestion
[tool.ruff.lint.flake8-copyright]
```

2024-05-22 07:52 UTC, natalian98 commented on pyproject.toml
> +[too.ruff.lint.flake8-copyright]
Does ruff check for copyright notices? I think we'd need to use `--preview` flag: https://docs.astral.sh/ruff/rules/missing-copyright-notice/

2024-05-22 07:57 UTC, BarcoMasile requested changes
Typo in `pyproject.toml` that Natalia caught

2024-05-23 07:58 UTC, BarcoMasile approved these changes

2024-05-28 09:47 UTC, nsklikas approved these changes

2024-05-28 15:51 UTC, merged